# Railway configuration for nOHACK backend service

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npx prisma migrate deploy && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 10

[build.nixpacks]
buildCommand = "cd backend && npm install && npx prisma generate && npm run build"