# Railway configuration for nOHACK backend service

[build]
builder = "NIXPACKS"

[deploy]
# Restart policy on failure
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacks]
# Install dependencies and build only the backend
buildCommand = "cd backend && npm install && npx prisma generate && npm run build"

# Start command for the backend server
startCommand = "cd backend && npx prisma migrate deploy && npm start"

# Node.js version to use
[variables]
NODE_VERSION = "18.20.8"

# Health check configuration
[healthcheck]
path = "/health"
interval = 30
timeout = 10
retries = 3